run-name: Build the Zoomer by @${{ github.actor }}
on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
      - name: Build with Maven
        run: |
          mvn clean install -DskipTests
      - name: Test with Maven
        run: |
          mvn verify --no-transfer-progress -DtrimStackTrace=false
